finance/auth/urls.py
from django.urls import path
from . import views

app_name = 'auth'
urlpatterns = [
        path('signin', views.signin, name='signin'),
        path('signout', views.signout, name='signout'),
        path('register', views.register, name='register'),
]

finance/brokers/urls.py
from django.urls import path
from . import views

app_name = 'brokers'
urlpatterns = [
    path('', views.show_users, name='brokerboard'),
    path('<int:customer_id>', views.specific_customer, name='specific_customer'),
    path('buy/<int:customer_id>', views.place_order, name='order'),
    path('orders/<int:customer_id>/<int:order_id>', views.view_order, name='broker_order_details'),
]

finance/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
        path('', views.dashboard, name='dashboard'),
        path('profile', views.profile, name='profile'),
        path('orders', views.all_orders, name='orders'),
        path('orders/<int:order_id>', views.order_details, name='order_details'),
        path('company/search', views.search_company, name='search_company'),
        path('company/<int:company_id>', views.search_company_with_id, name='company_search'),
        path('company/<str:company_name>', views.search_company_with_ticker, name='companySpecific'),
]

finance/finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('stocks/', include('stocks.urls')),
    path('brokers/', include('brokers.urls')),
    path('users/', include('users.urls')),
]

finance/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from stocks.models import Company


# Create your models here.
class Order(models.Model):
    """

    """
    BUY = 'B'
    SELL = 'S'

    TYPE = (
        (BUY, 'B'),
        (SELL, 'S')
    )

    order_id = models.AutoField(primary_key=True, unique=True)
    user_id = models.ForeignKey(User, related_name='order', on_delete=models.PROTECT)
    createdAt = models.DateTimeField(editable=False, auto_now_add=True)
    editedAt = models.DateTimeField(auto_now=True)
    order_type = models.CharField(
        max_length=10,
        choices=TYPE,
        default=BUY
    )

    
class OrderDetails(models.Model):
    """

    """
    order = models.ForeignKey(Order, unique=False, related_name='order_detail',
                              on_delete=models.PROTECT)
    stock_id = models.ForeignKey(Company, related_name='order_detail', on_delete=models.PROTECT, null=False, blank=False)
    purchase_price = models.DecimalField(blank=False, null=False, decimal_places=2, max_digits=10,
                                     default=0)
    sell_price = models.DecimalField(blank=False, null=False, decimal_places=2, max_digits=10,
                                         default=0)
    quantity = models.IntegerField(default=0, blank=False, null=False, max_length=10)
    createdAt = models.DateTimeField(editable=False, auto_now_add=True)
    editedAt = models.DateTimeField(auto_now=True)

finance/dashboard/views.py
from django.db import DatabaseError
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, QueryDict
from django.views.decorators.csrf import csrf_exempt
from dashboard.models import Order, OrderDetails
from django.contrib.auth.models import User
from rest_framework import serializers
from stocks.models import Company, StockDetails
from django.forms.models import model_to_dict
from .serializers import deserialize_user
from . import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.debug import sensitive_post_parameters, sensitive_variables
from django.db.models import Count
import random
import json
import requests
import re
import bs4 as bs
import pickle

# Create your views here.
@csrf_exempt
def dashboard(request):
    """
    returns recent orders by user
    """
    if request.user.is_authenticated:
        if request.method == 'GET':
            user = ""
            orders = ""
            try:
                user = User.objects.get(pk=request.user.id)
                orders = Order.objects.filter(user_id=request.user)
            except ObjectDoesNotExist:
                return HttpResponse('Error occurred with user or recent orders', status=404)
            sold = 0
            order_list = []
            for o in orders:
                if str(o.order_type) == 'B':
                    if OrderDetails.objects.filter(order_id=o.order_id).exists():
                        details = OrderDetails.objects.filter(order_id=o.order_id)
                        total = 0
                        for item in details:
                            total += item.quantity * item.purchase_price
                        order_list.append({'order_id': o.order_id, 'order_type': 'BUY',
                                           'order_date': o.createdAt,
                                           'total': total})

                elif str(o.order_type) == 'S':
                    sold += 1
                    if OrderDetails.objects.filter(order_id=o.order_id).exists():
                        details = OrderDetails.objects.filter(order_id=o.order_id)
                        total = 0
                        for item in details:
                            total += item.quantity * item.purchase_price
                        order_list.append({'order_id': o.order_id, 'order_type': 'SELL',
                                           'order_date': o.createdAt,
                                           'total': total})
            renderBody = {'data': order_list, 'total': len(order_list), 'sold': sold, 'broker': False}
            if user.profile.user_type == 'B':
                renderBody['broker'] = True
            return render(request, 'dashboard/index.html', renderBody, status=200)

        else:
            return HttpResponse("Method not allowed on /", status=405)
    else:
        return HttpResponse("Unauthorized: Not Logged In", status=401)

@csrf_exempt
@sensitive_post_parameters()
def search_company(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            count = Company.objects.aggregate(count=Count('company_id'))['count']
            random_index = random.randint(15, count - 1)
            random_start_index = random_index - 15
            sample = Company.objects.all()[random_start_index: random_index]
            companies = []
            for s in sample:
                if len(s.companyName) < 1000:
                    companies.append({"name": s.companyName,
                                    "symbol": s.symbol})

            return render(request, 'dashboard/search.html', {'data': companies}, status=200)
        elif request.method == 'POST':
            if request.user.is_authenticated:
                try:
                    stock_ticker = request.POST['stock'].lower()
                    print(stock_ticker)
                    company = Company.objects.get(symbol=stock_ticker)
                except ObjectDoesNotExist:
                    return HttpResponse("Company does not exist.", status=404)

                company_prof = {
                    "Company Name": company.companyName,
                    "Stock Ticker": company.symbol.upper(), 'Sector': company.sector,
                    'Industry': company.industry,
                    'Employees': company.employees,
                    'Website': company.homePage, 'Exchange': company.exchange
                }
                return render(request, 'dashboard/company_details.html',
                              {"company": company_prof, 'Description': company.description, },
                              status=200)
        else:
            return HttpResponse("Method not allowed on /", status=405)

    else:
        return HttpResponse('user is not authenticated', status=400)

@csrf_exempt
@sensitive_post_parameters()
def search_company_with_id(request, company_id):
    try:
        company = Company.objects.get(pk=company_id)
    except ObjectDoesNotExist:
        return HttpResponse("Company does not exist in db yet", status=404)
    if request.method == 'GET':
        if request.user.is_authenticated:
            company_prof = {
                "Company Name": company.companyName,
                "Stock Ticker": company.symbol.upper(), 'Sector': company.sector,
                'Industry': company.industry,
                'Employees': company.employees,
                'Website': company.homePage, 'Exchange': company.exchange
            }
            return render(request, 'dashboard/company_details.html',
                          {"company": company_prof, 'Description': company.description, },
                          status=200)
        else:
            return HttpResponse('user is not authenticated', status=400)
    else:
        return HttpResponse("Method not allowed on /", status=405)

@csrf_exempt
@sensitive_post_parameters()
def search_company_with_ticker(request, company_name):
    """ renders company info, updates and deletes company """
    company = ""
    user = ""
    try:
        company = Company.objects.get(symbol=company_name)
    except ObjectDoesNotExist:
        return HttpResponse("Company does not exist in db yet", status=404)
    try:
        user = User.objects.get(user=request.user)
    except ObjectDoesNotExist:
        return HttpResponse("User does not exist", status=404)
    if request.method == 'GET':
        if request.user.is_authenticated:
            company_prof = {
                "Company Name": company.companyName,
                "Stock Ticker": company.symbol.upper(), 'Sector': company.sector, 'Industry': company.industry,
                'Employees': company.employees,
                'Website': company.homePage, 'Exchange': company.exchange
            }
            return render(request, 'dashboard/company_details.html',
                          {"company": company_prof, 'Description': company.description,}, status=200)
        else:
            return HttpResponse('user is not authenticated', status=400)
    elif request.method == 'PATCH':
        if (
            request.user.is_authenticated and 
            (company.manager_id == request.user.id or 
            User.objects.get(user=request.user).user_type == 'A')
        ):
            body = json.loads(request.body.decode('utf-8'))
            for key, value in body.items():
                if company.field_exists(key):
                    setattr(company, key, value)
            company.save()
            return JsonResponse(model_to_dict(company), safe=False)
    elif request.method == 'DELETE':
        if (
            request.user.is_authenticated and 
            User.objects.get(user=request.user).user_type == 'A'
            ):
            company.delete()
            return HttpResponse('Delete was successful')
        else:
            return HttpResponse('Permission denied.', status=400)
    else:
        return HttpResponse("method not allowed", status=400)


@csrf_exempt
@sensitive_variables()
def profile(request):
    """

    :param request:
    :return:
    """
    if request.user.is_authenticated:
        try:
            user = User.objects.get(pk=request.user.id)
            profile = Profile.objects.get(user=user)
        except ObjectDoesNotExist:
            return HttpResponse("user does not exist", status=404)
        if request.method == 'GET':
            renderBody = {"data": deserialize_user(user)}
            if user.profile.user_type == 'B':
                renderBody["broker"] = True
            return render(request, 'dashboard/profile.html', renderBody, status=200)

        elif request.method == 'PATCH' or request.method == 'POST':
            user = User.objects.get(pk=request.user.id)

            if request.method == 'PATCH':
                data = request.body.decode('utf-8')
                data = json.loads(data)
            else:
                data = request.POST

            serializer = serializers.UserSerializer(data=data)

            if serializer.is_valid():
                fname = serializer.data.get('first_name')
                lname = serializer.data.get('last_name')
                email = serializer.data.get('email')
                phone = serializer.data.get('phone')
                description = serializer.data.get('description')
                country = serializer.data.get('country')

                if email != "":
                    user.email = email

                if fname != "":
                    user.first_name = fname

                if lname != "":
                    user.last_name = lname

                if phone != "":
                    profile.phone = phone

                if description != "":
                    profile.message = description

                if country != "":
                    profile.country = country

            user.save()
            profile.save()

finance/templates/dashboard/company.html
<ul>
    {% for k, v in company_prof.items %}
        <li>
            {{ k }}: {{ v }}
        </li>
    {% endfor %}
</ul>

finance/templates/dashboard/order_details.html
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Cart</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'stocks/cart/images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'stocks/cart/apple-touch-icon.png' %}">
    
    <!-- Bootstrap Fremwork Main Css -->
    <link rel="stylesheet" href="{% static 'stocks/cart/css/bootstrap.min.css' %}">
    <!-- All Plugins css -->
    <link rel="stylesheet" href="{% static 'stocks/cart/css/plugins.css' %}">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{% static 'stocks/cart/css/shortcode/shortcodes.css' %}">
    <!-- Theme main style -->
    <link rel="stylesheet" href="{% static 'stocks/cart/style.css' %}">
    <!-- Responsive css -->
    <link rel="stylesheet" href="{% static 'stocks/cart/css/responsive.css' %}">
    <!-- User style -->
    <link rel="stylesheet" href="{% static 'stocks/cart/css/custom.css' %}">

    <!-- Modernizr JS -->
    <script src="{% static 'stocks/cart/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <div class="wrapper fixed__footer">
        <!-- Start Header Style -->
        <header id="header" class="htc-header header--3 bg__white">
            <!-- Start Mainmenu Area -->
            <div id="sticky-header- with-topbar" class="mainmenu__area sticky__header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2 col-lg-2 col-6">
                        </div>
                        <!-- Start MAinmenu Ares -->
                        <div class="col-md-8 col-lg-8 d-none d-md-block">
                            <nav class="mainmenu__nav  d-none d-lg-block">
                            </nav>
                            
                            <div class="mobile-menu clearfix d-block d-lg-none">
                                <nav id="mobile_dropdown">
                                </nav>
                            </div>  
                        </div>
                        <!-- End MAinmenu Ares -->
                        <div class="col-md-2 col-lg-2 col-6">  
                            <ul class="menu-extra">
                                <li><a href="{% url 'dashboard:profile' %}"><span class="ti-user"></span></a></li>
                                <li class="cart__menu"><span class="ti-shopping-cart"></span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="mobile-menu-area"></div>
                </div>
            </div>
            <!-- End Mainmenu Area -->
        </header>
        <!-- End Offset Wrapper -->
        <!-- Start Bradcaump area -->
        <div>
            <div >
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Order {{order_id}}</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="/uniqlo/index.html">Dashboard</a>
                                  <span class="brd-separetor">/</span>
                                    <span class="breadcrumb-item active">Order Details</span>
                                    <h3 class="bradcaump-inner">Order Date - {{date}}</h3>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->
        <!-- cart-main-area start -->
        <div class="cart-main-area ptb--120 bg__white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-12">

                        <div class="buttons-cart">
                            {% if request.session.customer_id is None %}
                            <a href="/dashboard/orders">Back to All Orders</a>
                            {% else %}
                            <a href="{% url 'brokers:specific_customer' request.session.customer_id %}">Back to All Orders</a>
                            {% endif %}
                            <form method="post" action="/dashboard/orders/{{order_id}}">
                                <input type="submit" value="Sell Order" >
                            </form>
                        </div>
                        <form action="#" method="post">
                            <div class="table-content table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="product-thumbnail"></th>
                                            <th class="product-name">Company</th>
                                            <th class="product-price">Unit Price</th>
                                            <th class="product-quantity">Shares Traded</th>
                                            <th class="product-subtotal">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for k in data %}
                                        <tr>
                                            <td class="product-thumbnail"><a href="/dashboard/company/{{k.ticker}}"><img src="//logo.clearbit.com/{{ k.image }}?size=50"></a></td>
                                            <td class="product-name"><a href="/dashboard/company/{{k.ticker}}">{{ k.company }}</a></td>
                                            <td class="product-price"><span class="amount">{{ k.price }}</span></td>
                                            <td class="product-subtotal">{{ k.quantity }}</td>
                                            <td class="product-subtotal">{{ k.total }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-8 col-sm-12">
                                </div>
                                <div class="col-md-4 col-sm-12 ">
                                    <div class="cart_totals">
                                        <h2>Order Total</h2>
                                        <table>
                                            <tbody>
                                                <tr class="cart-subtotal">
                                                    <th>Subtotal</th>
                                                    <td><span class="amount">${{sum}}</span></td>
                                                </tr>
                                                <tr class="shipping">
                                                    <th>Commission</th>
                                                    <td>$0.00</td>
                                                    </td>
                                                </tr>
                                                <tr class="order-total">
                                                    <th>Total</th>
                                                    <td>
                                                        <strong><span class="amount">${{sum}}</span></strong>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jquery latest version -->
    <script src="{% static 'stocks/cart/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap Framework js -->
    <script src="{% static 'stocks/cart/js/popper.min.js' %}"></script>
    <script src="{% static 'stocks/cart/js/bootstrap.min.js' %}"></script>
    <!-- All js plugins included in this file. -->
    <script src="{% static 'stocks/cart/js/plugins.js' %}"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="{% static 'stocks/cart/js/main.js' %}"></script>

</body>

</html>

finance/templates/dashboard/orders_table.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="../../static/dashboard/plugins/images/favicon.png">
    <title>All Orders</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'dashboard/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{% static 'dashboard/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css' %}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{% static 'dashboard/css/animate.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{% static 'dashboard/css/colors/blue-dark.css' %}" id="theme" rel="stylesheet">  
    <script src="https://use.fontawesome.com/96b409b62e.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars
"></i></a>
                <div class="top-left-part"><a class="logo" href="\"><b><img src="../../static/dashboard/plugins/images/pixeladmin-logo.png" alt="home" /></b><span class="hidden-xs">
                    <img src="../../static/dashboard/plugins/images/pixeladmin-text.png" alt="home" /></span></a></div>
                <ul class="nav navbar-top-links navbar-left m-l-20 hidden-xs">
                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li>
                        <a class="button button-sm button-shadow"
                           href="{% url 'auth:signout' %}">Signout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Left navbar-header -->
       <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse slimscrollsidebar">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="\dashboard" class="waves-effect">
                            <i class="fa fa-table fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">Dashboard</span></a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:orders' %}" class="waves-effect">
                            <i class="fa fa-table fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">My Trade History</span></a>
                    </li>
                    <li>
                        <a href="/stocks/search" class="waves-effect">
                            <i class="fa fa-columns fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">Trade Stocks</span></a>
                    </li>
                    <li>
                        <a href="/dashboard/company/search" class="waves-effect">
                            <i class="fa fa-columns fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">Search Company Info</span></a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:profile' %}" class="waves-effect">
                            <i class="fa fa-user fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">Profile</span></a>
                    </li>
                    {% if broker %}
                    <li>
                        <a href="/brokers/" class="waves-effect">
                            <i class="fa fa-columns fa-fw" aria-hidden="true"></i>
                            <span class="hide-menu">Broker Board</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- Left navbar-header end -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">My Trade History</h4> </div>
                        <ol class="breadcrumb">
                            <li><a href="#">Dashboard</a></li>
                            <li class="active">My Trade History</li>
                        </ol>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="white-box">

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Order #</th>
                                            <th>Date</th>
                                            <th>Type</th>
                                            <th># Companies</th>
                                            <th>Total Shares Traded</th>
                                            <th>Total Sell Price</th>
                                            <th>Total Purchase Price</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for k in data %}
                                    <tr>
                                        <td>{{ k.order_id }}</td>
                                        <td>{{ k.order_date }}</td>
                                        <td>{{ k.order_type }}</td>
                                        <td>{{ k.companies }}</td>
                                        <td>{{ k.shares }}</td>
                                        <td>{{ k.sell }}</td>
                                        <td>{{ k.total }}</td>
                                        <td><form action='/dashboard/orders/{{k.order_id}}'>
                                            <input value="View Details" type="submit" class="form-control"></form></td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="{% static 'dashboard/plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'dashboard/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'dashboard/js/jquery.slimscroll.j' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dashboard/js/waves.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dashboard/js/custom.min.js' %}"></script>
</body>

</html>